# Generated by Django 5.1 on 2024-08-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0005_remove_tasks_due_date_remove_tasks_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='featured_order',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
    ]
