# Generated by Django 5.1 on 2024-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0006_remove_courses_featured_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='helper_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
