# Generated by Django 5.1 on 2024-08-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0007_courses_helper_links_courses_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_students', to='Prmath.courses')),
                ('current_courses', models.ManyToManyField(blank=True, to='Prmath.courses')),
                ('current_projects', models.ManyToManyField(blank=True, to='Prmath.projects')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prmath.profile')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='Prmath.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('courses_taught', models.ManyToManyField(blank=True, related_name='teachers', to='Prmath.courses')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prmath.profile')),
                ('projects_created', models.ManyToManyField(blank=True, related_name='teachers', to='Prmath.projects')),
                ('skills', models.ManyToManyField(blank=True, related_name='teachers', to='Prmath.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
