# Generated by Django 5.1 on 2024-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0008_alter_profile_role_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
