# Generated by Django 5.1 on 2024-08-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0009_remove_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Prmath.profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='teacher_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prmath.profile'),
        ),
    ]
