# Generated by Django 5.1 on 2024-08-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0011_alter_courses_teacher_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='teacher_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prmath.profile'),
        ),
    ]
