# Generated by Django 5.1 on 2024-08-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0013_profile_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.AlterField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
