# Generated by Django 5.1 on 2024-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0015_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
