# Generated by Django 5.1 on 2024-08-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0016_studentprofile_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_active',
            new_name='last_seen',
        ),
    ]
