# Generated by Django 5.1 on 2024-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prmath', '0017_rename_last_active_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
